# Missing data

Of the 78 experiments that met the eligibility criteria of this meta-analysis, 25 were excluded because of missing data. Those 25 experiments included 13 experiments that reported a statistically significant result, along with 12 that failed to find a significant self-controlled learning effect. Among the 13 experiments with missing data reporting a significant self-control benefit, one reported an inappropriate analysis (Hemayattalab et al.2013),[^6] one reported statistics that do not match the experimental design (Jalalvand et al., 2019),[^7] one reported significant effects on a partial analysis of their data rather than overall (Brydges et al., 2009), and one was previously identified by Lohse and colleagues (2016) as an outlier study (Carter & Patterson, 2012). The meta-analysis may have been strengthened by the exclusion of these results (Stanley et al., 2010).

[^6]:Although data were collected in one dimension using concentric circles, AE and a measure of dispersion were analyzed together in a MANOVA. This measure of dispersion is not an accurate reflection of variability on a two-dimensional task for reasons described by Hancock et al. (1995).

[^7]:A subgroup analysis involving two groups $n$ = 15 was reported with $df$ = 56. The article reports $r^2$ effect sizes associated with each test that cannot be reproduced with the reported statistics or best guesses.

Among the remaining nine experiments reporting a significant effect with missing data, two reported effects collapsed across immediate and delayed retention only (Patterson et al., 2013; Wu & Magill, 2011), two reported null effects on a higher priority measure and did not include sufficient data to calculate the effect size, while reporting a significant effect on a lower priority measur((Wulf et al., 2001; Wulf et al., 2005, both studies were included in the primary *p*-curve analysis), and five compared three or more groups in an omnibus ANOVA and reported the group effect as significant but did not include sufficient data to calculate the effect size for the self-control versus yoked comparison (Chen et al., 2002; Ghorbani, 2019; Huet et al., 2009; Janelle et al., 1997; Norouzi et al., 2016)

